"""empty message

Revision ID: 3fb5610faa8f
Revises: 3b5b5c7a0ef6
Create Date: 2019-10-04 23:02:40.918927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb5610faa8f'
down_revision = '3b5b5c7a0ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('rooms', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('roommateGender', sa.String(), nullable=True),
    sa.Column('pets', sa.String(), nullable=True),
    sa.Column('shared', sa.String(), nullable=True),
    sa.Column('rentMin', sa.Float(), nullable=True),
    sa.Column('rentMax', sa.Float(), nullable=True),
    sa.Column('ensuite', sa.String(), nullable=True),
    sa.Column('favorites', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
