"""empty message

Revision ID: f2f6fbf5c5d7
Revises: 3fb5610faa8f
Create Date: 2019-10-04 23:35:34.076375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2f6fbf5c5d7'
down_revision = '3fb5610faa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lister', sa.String(), nullable=True),
    sa.Column('roommateGender', sa.String(), nullable=True),
    sa.Column('numAvailable', sa.Integer(), nullable=True),
    sa.Column('pets', sa.String(), nullable=True),
    sa.Column('shared', sa.String(), nullable=True),
    sa.Column('rent', sa.Float(), nullable=True),
    sa.Column('ensuite', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('listed', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('users', 'rooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rooms', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('users', 'listed')
    op.drop_table('rooms')
    # ### end Alembic commands ###
